robot_name: "Marco"

base_diameter: 0.2
wheel_radius: 0.05

rotary_encoder: {
	pulse_per_rev: 132,
	pulse_per_meter: 426,
}

imu_sensor: {
	bearing_scale: 10,
	accel_scale: 0.01,
	gyro_scale: 0.0625,
}

motor_driver: {
	max_angular_velocity: 39.0,
	timeout: 2,
	rate: 10,
}
